Algoritmo "exe4_0a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : alunocetam22
// Data atual  : 25/03/2022

Var
// Seção de Declarações das variáveis
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


   enquanto (contador < 11) faca
      escreva(contador)
      contador <- contador + 1
      fimenquanto

Fimalgoritmo