Algoritmo "Maior-Numero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2022

Var
// Seção de Declarações das variáveis 
n1 , n2 : real

Inicio

//------------------------------------------------------------------------+
// Passando valores iniciais para as variáveis
//------------------------------------------------------------------------+

n1 <- 0

n2 <- 0

//------------------------------------------------------------------------+
// Apresentação
//------------------------------------------------------------------------+

escreval ("")

escreval (" Software recebe dois números quaisquer (n1 e n2).")

escreval ("")

escreval (" Verifica qual número é MAIOR.")

escreval ("")

escreval (" Exibe em tela o MAIOR número.")

escreval ("")

escreval ("")



//------------------------------------------------------------------------+
// Entrada de dados
//------------------------------------------------------------------------+

escreval ("")

escreva (" 01 Numero -> ")

leia (n1)

escreval ("")

escreva (" 02 Numero -> ")

leia (n2)

escreval ("")

escreval ("")



//------------------------------------------------------------------------+
// Saída de dados
//
// Verificando valores e definindo conceito
//------------------------------------------------------------------------+

se (n1 = n2) entao

   escreval (" Conceito -> Os números são IGUAIS!")

senao

   se (n1 > n2) entao

      escreval (" Conceito ->", n1, " é MAIOR que", n2, ".")

   senao

      escreval (" Conceito ->", n2, " é MAIOR que", n1, ".")

   fimse

fimse



//------------------------------------------------------------------------+
// Pulando linhas
//------------------------------------------------------------------------+

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

escreval ("")

FimAlgoritmo
